Repository naramzik/twitter-namecard, pull requests merged in 2024-03, with the labels that each got.

#66 feat: 명함 상세 페이지 UI 개선
  .vscode/settings.json
  package.json
  public/delete.png
  public/edit.png
  public/github.png
  public/instagram.png
  public/link.png
  public/share.png
  public/twitter-blue-mark.png
  src/components/icons/CardIcon.tsx
  src/components/icons/CreateIcon.tsx
  src/components/icons/HomeIcon.tsx
  src/components/ui/BottomNavigation.tsx
  src/hooks/styles/getTextColor.ts
  src/pages/[id]/index.tsx
  src/pages/api/cards/[cardId].ts
  yarn.lock
Labels: enhancement

#72 명함 이미지 다운로드 기능을 추가
  package.json
  src/pages/api/cards/[cardId]/NanumGothic-Regular.ttf
  src/pages/api/cards/[cardId]/Pretendard-Bold.woff
  src/pages/api/cards/[cardId]/Pretendard-Regular.woff
  src/pages/api/cards/[cardId]/img-download.tsx
  src/pages/api/cards/[cardId]/thumbnail.tsx
  yarn.lock
Labels: enhancement

#73 feat: 폼 유효성 검사 추가
  src/components/card/CardForm.tsx
  src/pages/[id]/edit/index.tsx
  src/utils/showToastMessage.ts
Labels: enhancement

#74 feat: 명함 수정시 비밀번호 필드 숨기기
  src/components/card/CardForm.tsx
Labels: enhancement

#76 feat: QR코드에 숏링크 URL 연결하기
  src/components/modal/BottomSheet.tsx
  src/components/modal/QRModal.tsx
  src/hooks/queries/useCreateShortLink.ts
Labels: enhancement

#77 refactor: 백엔드 코드 리팩토링
  package.json
  prisma/schema.prisma
  src/pages/api/cards/[cardId].ts
  src/pages/api/cards/[cardId]/login.ts
  src/pages/api/cards/[cardId]/logout.ts
  src/pages/api/cards/index.ts
  src/pages/api/twitter-info/[twitterId]/index.ts
  src/utils/prisma.ts
  src/utils/switchCrawler.ts
  yarn.lock
Labels: refactor

#75 feat: Supabase 타입 젠
  database.types.ts
  package.json
  src/utils/supabase.js
  src/utils/supabase.ts
  yarn.lock
Labels: enhancement

#81 feat: 404페이지, 메타 태그 추가
  public/favicon.ico
  public/images/404.png
  public/images/add.png
  public/images/card.png
  public/images/copy.png
  public/images/delete.png
  public/images/download.png
  public/images/edit.png
  public/images/empty.png
  public/images/github.png
  public/images/hide.png
  public/images/instagram.png
  public/images/left-arrow.png
  public/images/link.png
  public/images/naramzik-namecard.png
  public/images/next.svg
  public/images/qr-code.png
  public/images/search.png
  public/images/share.png
  public/images/twitter-blue-mark.png
  public/images/twitter.png
  public/images/vercel.svg
  public/images/view.png
  src/components/SEO/SEO.tsx
  src/components/card/CardForm.tsx
  src/components/form/Password.tsx
  src/components/modal/BottomSheet.tsx
  src/components/ui/Title.tsx
  src/pages/404.tsx
  src/pages/card/[cardId]/index.tsx
  src/pages/card/index.tsx
  src/pages/create-card/index.tsx
  src/pages/index.tsx
Labels: enhancement

#82 feat: 모든 공유하기 url을 숏링크로 수정
  src/components/SEO/SEO.tsx
  src/components/modal/BottomSheet.tsx
  src/components/modal/QRModal.tsx
  src/pages/card/[cardId]/index.tsx
Labels: enhancement

#83 fix: 명함 정보를 가져올 때 잘못된 image_url 값 변경
  src/pages/api/cards/[cardId].ts
  src/pages/api/cards/index.ts
Labels: bug

#84 feat: 명함 아이템 스타일링 및 메뉴바 비활성화 오류 해결
  src/components/SEO/SEO.tsx
  src/components/card/CardItem.tsx
  src/components/ui/BottomNavigation.tsx
  src/pages/card/[cardId]/index.tsx
Labels: enhancement

#85 feat: 명함 이미지 로딩시 배경 설정
  src/components/card/CardItem.tsx
  src/components/ui/BottomNavigation.tsx
  src/pages/card/[cardId]/index.tsx
Labels: enhancement

#86 fix: QR코드 중앙에 있는 이미지를 표시하지 못하는 오류 해결
  src/components/SEO/SEO.tsx
  src/pages/card/[cardId]/index.tsx
Labels: bug

#89 feat: twitter meta tag 수정
  src/components/SEO/SEO.tsx
Labels: enhancement

#90 feat: 숏링크 리다이렉트
  next.config.js
  src/pages/api/short-link/[shortLink]/index.ts
  src/utils/errorHandler.ts
Labels: enhancement

#92 fix: 숏링크 경로에 s 추가
  src/components/modal/BottomSheet.tsx
  src/components/modal/QRModal.tsx
Labels: bug

#93 feat: 구글 애널리틱스 연결
  src/components/SEO/SEO.tsx
Labels: enhancement

#95 feat: 에러 메시지 수정
  src/utils/showToastMessage.ts
Labels: enhancement

#96 feat: 구글 애널리틱스 추가연결
  package.json
  src/components/SEO/SEO.tsx
  src/libs/gtags.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  types.d.ts
  yarn.lock
Labels: enhancement

#97 feat: 비밀번호 불일치 오류 메시지 추가
  src/utils/showToastMessage.ts
Labels: enhancement

#98 feat: 트위터 공유 메시지 수정
  src/components/modal/BottomSheet.tsx
Labels: enhancement

#99 docs: 리드미 틀 추가
  README.md
  public/docs/github_biyam.jpg
  public/docs/github_cottonup.png
  public/docs/github_nabi.png
Labels: documentation

#100 feat: 에러 메시지 추가
  src/utils/showToastMessage.ts
Labels: enhancement

#102 feat: cursor-pointer 추가 및 link 태그로 변경
  src/components/card/CardItem.tsx
Labels: enhancement

#103 fix: 폼 검증 로직 추가
  src/components/card/CardForm.tsx
Labels: bug

#107 카드 검색 기능 추가
  src/hooks/queries/useGetCards.ts
  src/pages/api/cards/index.ts
  src/pages/index.tsx
Labels: enhancement

#114 feat: 검색 기능 추가
  src/components/layout/HomeLayout.tsx
  src/hooks/queries/useGetCards.ts
  src/pages/api/cards/index.ts
  src/pages/index.tsx
Labels: enhancement

#115 fix: 검색창, 커피한잔 스타일 수정
  src/components/layout/HomeLayout.tsx
  src/pages/index.tsx
Labels: bug

#112 fix: 명함 컴포넌트 ui 수정 및 글자수 제한, 명함 상세 페이지에서 로고 깨지는 오류 해결
  src/components/card/CardForm.tsx
  src/components/card/NameCard.tsx
  src/pages/api/cards/[cardId]/thumbnail.tsx
  src/pages/card/[cardId]/index.tsx
Labels: bug

#116 fix: 명함 OG 이미지 스타일 변경
  src/pages/api/cards/[cardId]/thumbnail.tsx
Labels: bug

#117 feat: 아이디 input 앞에 @ 추가, url 앞에 https:// 글자 추가
  src/components/card/CardForm.tsx
  src/pages/card/[cardId]/index.tsx
Labels: enhancement

#118 feat: new를 포함한 명함 설명 ui 수정
  src/components/card/CardItem.tsx
Labels: bug
