Repository naramzik/twitter-namecard, pull requests merged in 2024-04, with the labels that each got.

#121 docs: 백엔드 기술스택 리드미 업데이트
  README.md
Labels: documentation

#106 feat: 무한 스크롤 구현
  package.json
  src/hooks/queries/useGetCards.ts
  src/pages/api/cards/index.ts
  src/pages/index.tsx
  yarn.lock
Labels: enhancement

#122 refactor: 성능 및 접근성 개선
  src/components/card/CardItem.tsx
  src/pages/_app.tsx
Labels: refactor

#123 docs: 리드미에 주요 기능 설명 추가
  README.md
  docs/github_biyam.jpg
  docs/github_cottonup.png
  docs/github_nabi.png
  docs/qrcode-share.gif
  docs/twitter-share.gif
  public/docs/github_biyam.jpg
  public/docs/github_cottonup.png
  public/docs/github_nabi.png
Labels: documentation

#124 fix: 스크롤이 끝까지 내려가도 다음 페이지가 불려오지 않는 오류 해결
  src/pages/index.tsx
Labels: bug
